name: CI for Dev Unit Tests

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Check branch name
      if: startsWith(github.ref, 'refs/heads/test/')
      run: |
        tag_branch="$(cut -d'/' -f1 <<< ${GITHUB_REF#refs/heads/})"
        name_branch="$(cut -d'/' -f2 <<< ${GITHUB_REF#refs/heads/})"
        echo "TAG_BRANCH_SHORT=$(echo 'meowmeow')" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo 'meowmeow' | cut -c 1-6)" >> $GITHUB_ENV
        echo $TAG_BRANCH_SHORT
        echo $GITHUB_SHA_SHORT
        echo 'true'

    - name: Test
      run: echo $GITHUB_SHA_SHORT
