name: CI for Dev Unit Tests

on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Check branch name
      run: |
        tag_branch="$(cut -d'/' -f1 <<< ${GITHUB_REF#refs/heads/})"
        name_branch="$(cut -d'/' -f2 <<< ${GITHUB_REF#refs/heads/})"
        
        echo "${GITHUB_REF}"
        echo "NAME_BRANCH=$(echo $name_branch)" >> $GITHUB_ENV
        echo "TAG_BRANCH=$(echo $tag_branch)" >> $GITHUB_ENV
        
        echo "$tag_branch"
        echo "$name_branch"
        echo $TAG_BRANCH
        echo $NAME_BRANCH
