name: CI for Dev Unit Tests

on: push
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Check branch name
      run: |
        tag_branch="$(cut -d'/' -f1 <<< ${GITHUB_REF#refs/heads/})"
        name_branch="$(cut -d'/' -f2 <<< ${GITHUB_REF#refs/heads/})"
        echo "TAG_BRANCH_SHORT=$(echo 'meowmeow')" >> $GITHUB_ENV
        echo "$tag_branch"
        echo "$name_branch"
        echo ${{env.TAG_BRANCH_SHORT}}
        echo ${{env.NAME_BRANCH_SHORT}}
