name: gsheet.action test
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'get_branch_id'
        run: | 
          echo "##[set-output name=branch;]$(echo $(cut -d'/' -f2 <<< ${GITHUB_REF#refs/heads/}))"

      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.2.0 # you can specify '@release' to always have the latest changes
        env: 
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        with:
          spreadsheetId: 1quwJHo9mpur_1BPpvgaj03DGeDl8EhAuPRxd9AJxF4c
          commands: | # list of commands, specified as a valid JSON string
            [              
              { 

                "command": "appendData", "args": { "worksheetTitle": "Code Coverage", 
                "minCol": 2,
                "data": [["${{steps.get_branch_id.outputs.branch}}", "0", "40","100"]] }
              }
            ]


      - name: Begin Pytest
        run: |
          ls
          mv ./tests/*.* ./
          pytest --cov -v --junitxml=report.xml
          echo "check for report.xml:"
          ls
      - if: ${{failure()}}
        name: Create Issues
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: workflow-failed
          body: Workflow failed for commit ${{github.sha}} @ ${{github.ref}}
