name: gsheet.action test
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'get_branch_id'
        run: | 
          echo "##[set-output name=branch;]$(echo $(cut -d'/' -f2 <<< ${GITHUB_REF#refs/heads/}))"

      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.2.0 # you can specify '@release' to always have the latest changes
        env: 
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        with:
          spreadsheetId: 1quwJHo9mpur_1BPpvgaj03DGeDl8EhAuPRxd9AJxF4c
          commands: | # list of commands, specified as a valid JSON string
            [              
              { 

                "command": "appendData", "args": { "worksheetTitle": "Code Coverage", 
                "minCol": 2,
                "data": [["${{steps.get_branch_id.outputs.branch}}", "0", "40","100"]] }
              }
            ]


      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
