name: Pytest Documentation

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: PyTest
        run: python -m pytest --junit-xml report.xml

      - name: "Publish Unit Tests Results"
        uses: EnricoMi/publish-unit-test-result-action@v1.25
        if: always()
        with:
          files: report.xml
