name: Pytest Documentation

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: CINotify Email
        uses: cinotify/github-action@v1.1.0
        with:
          to: 'jasonleequansheng@gmail.com'
          subject: 'building main'
          body: 'This is a notification from GitHub actions.'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      - name: PyTest
        run: python -m pytest --junit-xml=report.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.24
        if: always()
        with:
          files: report.xml
          

