name: CI for QA

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
      
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: np-devops-team1/DevOps_Oct2021_Team1_Test
        
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        files: test_main.py
        
    - name: Begin Pytest
      run: |
        python -m pytest test --junit-xml pytest.xml

    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        path: pytest.xml
        
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: artifacts/**/*.xml
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
         name: Unit Test Results
         path: |
            test-results/*.xml
    
