name: CI for QA

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
      
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: np-devops-team1/DevOps_Oct2021_Team1_Test
        
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        files: test_main.py
        
    - name: Begin Pytest
      run: |
        python -m pytest test_main.py --junit-xml pytest.xml

    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: pytest.xml
        
  publish-test-results:
    name: publish test results
    needs: build
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: results
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
          
      - name: Get XML
        id: getxml
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: artifacts/**/*.xml
          xpath: '//testsuites'
        
      - name: Update Series
        run: |
          echo ${{ steps.getxml.outputs.info }}

