name: Deployment

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Prepare for Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile into Executable
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
